package uz.code.ishvakansiyabot.enums;

public enum UserStep {
    CREATING, ACCEPTING_NEW_USER, END, ADD_VACANCY, ACCEPTING_VACANCY, EDIT_VACANCY, ADD_RESUME, ACCEPTING_RESUME, EDIT_RESUME, SEARCH_VACANCY, SEARCH_RESUME, SEND_FEEDBACK, ADMIN_PANEL, SETTINGS, PROFILE, EDIT_PROFILE, DELETING_PROFILE, EDIT_NAME, EDIT_AGE, EDIT_ADDRESS;
}
